from .DBbaseline import (
    setup_mysql_database,
    get_mysql_connection,
)
from .DBcreateTables import (
    create_tables,
    newTableClass,
    newTableConnectionData,
    newTableDocuments,
    newTableIPs,
    newTablePersonalData,
    newTableUsers,
    newTableResults,
    newTableBlacklistedEmails,
    newTableBlacklistedIPs,
    newTableRegistrationTokens,
)
from .DBinsertTables import (
    insertNewClass,
    insertNewConnectionData,
    insertNewDocument,
    insertNewIP,
    insertNewPersonalData,
    save_quiz_history,
    insertNewUser,
    insertNewBlacklistedEmail,
    insertNewBlacklistedIP,
    insertNewRegistrationToken,
)
from .DBselectTables import (
    get_user_profile_tier1,
    get_user_profile_tier2,
    getDataFromCellNumber,
    getDataFromEmail,
    getDataFromIPcreated,
    getDataFromNIF,
    getUserIdFromEmail,
    getHashFromEmail,
    getEmailFromUsername,
    getQuestionFromQid,
    get_quiz_history_for_user,
    getQuestionIDsForYear,
    get_quiz_history_by_uuid,
    isEmailBlacklisted,
    getRegistrationToken,
    getRegistrationTokenByEmailOrIP,
    isIpBlacklisted,
)
from .DBdeleteTables import (
    deleteRegistrationToken,
    deleteExpiredRegistrationTokens,
)
from .DBupdateTables import refresh_last_login_and_ip
# from .DBmodifyTables import updateValue

__all__ = [
    "setup_mysql_database",
    "create_tables",
    "newTableClass",
    "newTableConnectionData",
    "newTableDocuments",
    "newTableIPs",
    "newTablePersonalData",
    "newTableUsers",
    "newTableResults",
    "newTableBlacklistedEmails",
    "newTableBlacklistedIPs",
    "newTableRegistrationTokens",
    "insertNewClass",
    "insertNewConnectionData",
    "insertNewDocument",
    "insertNewIP",
    "insertNewPersonalData",
    "save_quiz_history",
    "insertNewUser",
    "get_user_profile_tier1",
    "get_user_profile_tier2",
    "get_quiz_history_for_user",
    "getDataFromCellNumber",
    "getDataFromEmail",
    "getDataFromIPcreated",
    "getDataFromNIF",
    "getUserIdFromEmail",
    "refresh_last_login_and_ip",
    "getHashFromEmail",
    "getEmailFromUsername",
    "getQuestionIDsForYear",
    "get_mysql_connection",
    "isEmailBlacklisted",
    "insertNewBlacklistedEmail",
    "insertNewBlacklistedIP",
    "insertNewRegistrationToken",
    "getRegistrationToken",
    "getRegistrationTokenByEmailOrIP",
    "deleteRegistrationToken",
    "deleteExpiredRegistrationTokens",
    "isIpBlacklisted",
]