CREATE TABLE IF NOT EXISTS iplist (
ip_id   INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
ip_value TEXT,
ip_valid INTEGER DEFAULT TRUE,
first_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
login_count INTEGER NOT NULL DEFAULT 1,
FOREIGN KEY (user_id) REFERENCES users(user_id)
);