CREATE TABLE IF NOT EXISTS qresults (
q_uuid  TEXT PRIMARY KEY UNIQUE,
q_score    INTEGER NOT NULL,
q_year INTEGER,
q_percent INTEGER,
q_resp TEXT NOT NULL,
n_correct    INTEGER NOT NULL,
n_wrong     INTEGER NOT NULL,
n_skip     INTEGER NOT NULL,
user_id  INTEGER,
start_ts TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
finish_ts  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
