DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS iplist;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS connection;
DROP TABLE IF EXISTS personal;
DROP TABLE IF EXISTS classes;

-- DROP Table if EXISTS sqlite_sequence;