CREATE TABLE IF NOT EXISTS iplist (
  ip_id      INT PRIMARY KEY AUTO_INCREMENT,
  user_id    CHAR(36),
  ip_address VARCHAR(45) NOT NULL,
  createdatts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastusedts  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  use_count   INT NOT NULL DEFAULT 1,
  vpn_check   BOOLEAN NOT NULL DEFAULT FALSE,
  vpn_valid   BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_iplist_user
    FOREIGN KEY (user_id) REFERENCES users(user_id)
) ENGINE=InnoDB;
